import json
import subprocess
import time
from pathlib import Path

from aac.execution.contracts import (
    ExecutionResult, ExecutionStatus, ExecutionTarget, TestOutcome, TestResult,
)


class PytestExecutor:
    """Controlled pytest executor. It only accepts normalized pytest test IDs."""

    runner = "pytest"

    def execute(self, request_id: str, target: ExecutionTarget, timeout_seconds: int = 300) -> ExecutionResult:
        root = Path(target.project_path).expanduser().resolve()
        if not root.is_dir():
            return ExecutionResult(request_id, ExecutionStatus.REJECTED, error="Project path does not exist")
        if target.runner != self.runner or not target.test_ids:
            return ExecutionResult(request_id, ExecutionStatus.REJECTED, error="Unsupported or empty pytest target")

        # Only normalized IDs generated by the pytest adapter are accepted.
        if any(not item.startswith("pytest:") for item in target.test_ids):
            return ExecutionResult(request_id, ExecutionStatus.REJECTED, error="Invalid pytest test ID")

        started = time.time()
        command = ["pytest", "--json-report", "--json-report-file=-", "-q"] + self._resolve_nodeids(root, target.test_ids)
        try:
            completed = subprocess.run(command, cwd=root, capture_output=True, text=True, timeout=timeout_seconds, check=False)
        except subprocess.TimeoutExpired:
            return ExecutionResult(request_id, ExecutionStatus.ERROR, started_at=str(started), error="pytest execution timed out")
        except OSError as exc:
            return ExecutionResult(request_id, ExecutionStatus.ERROR, started_at=str(started), error=f"Unable to start pytest: {exc}")

        results = self._parse_report(completed.stdout)
        status = ExecutionStatus.PASSED if completed.returncode == 0 else ExecutionStatus.FAILED
        return ExecutionResult(
            request_id=request_id, status=status, results=results,
            started_at=str(started), completed_at=str(time.time()),
            error=None if completed.returncode == 0 else completed.stderr[-4000:],
        )

    def _resolve_nodeids(self, root: Path, ids: list[str]) -> list[str]:
        # Discovery IDs are deliberately not reversible. Until the adapter exposes
        # a signed/validated execution target, execute only source paths already
        # present in metadata at a future orchestration layer.
        raise ValueError("Pytest execution target resolution is not yet wired")

    def _parse_report(self, stdout: str) -> list[TestResult]:
        # Kept isolated so report format changes do not leak into domain contracts.
        try:
            data = json.loads(stdout)
        except json.JSONDecodeError:
            return []
        results = []
        for item in data.get("tests", []):
            outcome = item.get("outcome", "error")
            if outcome not in {x.value for x in TestOutcome}:
                outcome = "error"
            results.append(TestResult(test_id=item.get("nodeid", "unknown"), outcome=TestOutcome(outcome), duration_seconds=item.get("duration")))
        return results
